Rush page, not complete
UCSD-Theta-Tau-Website/TT-Website pull request #24
Opened 2023-09-12 05:15 UTC by amoghm01

2023-09-12 17:25 UTC, henrybliu requested changes
Navbar shouldn't be touched, page should scale w different views, banner should fill up the full screen

2023-09-24 05:46 UTC, amoghm01 commented
fixed issues, finished up to FAQ

2023-09-26 08:22 UTC, henrybliu commented
- original issues fixed
needed fixes:
- max width for larger screens (maybe look at Jordan's page as an example)
- increase size of the rush process timeline

2023-09-30 20:30 UTC, henrybliu approved these changes

2023-09-30 20:30 UTC, merged